/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainFrame;

/**
 *
 * @author emmanuelchibua
 */
public class PhysicalMetrics extends javax.swing.JPanel {

    /**
     * Creates new form PhysicalMetrics
     */
    public PhysicalMetrics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weightLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        bmiLabel = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        bmiTextField = new javax.swing.JTextField();
        physicalMetricsSubmitButton = new javax.swing.JButton();
        instructionTitleLabel = new javax.swing.JLabel();
        bmiLabel1 = new javax.swing.JLabel();
        bmiLabel2 = new javax.swing.JLabel();
        bmiLabel3 = new javax.swing.JLabel();
        bmiTextField1 = new javax.swing.JTextField();
        bmiTextField2 = new javax.swing.JTextField();
        bmiTextField3 = new javax.swing.JTextField();
        bmiTextField4 = new javax.swing.JTextField();
        bmiTextField5 = new javax.swing.JTextField();
        bmiTextField6 = new javax.swing.JTextField();
        bmiTextField7 = new javax.swing.JTextField();
        bmiTextField8 = new javax.swing.JTextField();
        bmiLabel4 = new javax.swing.JLabel();
        bmiLabel5 = new javax.swing.JLabel();
        bmiLabel6 = new javax.swing.JLabel();
        bmiLabel7 = new javax.swing.JLabel();
        bmiLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bmiLabel9 = new javax.swing.JLabel();
        bmiTextField9 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        weightLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        weightLabel.setForeground(new java.awt.Color(0, 102, 102));
        weightLabel.setText("Weight");

        heightLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        heightLabel.setForeground(new java.awt.Color(0, 102, 102));
        heightLabel.setText("Height");

        bmiLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel.setText("Right arm");

        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });

        physicalMetricsSubmitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalMetricsSubmitButton.setForeground(new java.awt.Color(0, 102, 102));
        physicalMetricsSubmitButton.setText("SUBMIT");
        physicalMetricsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalMetricsSubmitButtonActionPerformed(evt);
            }
        });

        instructionTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        instructionTitleLabel.setForeground(new java.awt.Color(0, 102, 102));
        instructionTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionTitleLabel.setText("Please input your body metric data below.");

        bmiLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel1.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel1.setText("Shoulder");

        bmiLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel2.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel2.setText("Chest");

        bmiLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel3.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel3.setText("Left arm");

        bmiLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel4.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel4.setText("Hip");

        bmiLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel5.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel5.setText("Right thigh");

        bmiLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel6.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel6.setText("Left thigh");

        bmiLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel7.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel7.setText("Right calf");

        bmiLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel8.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel8.setText("Left calf");

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("in cm");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("in cm");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("in cm");

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("in cm");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("in cm");

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("in cm");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("in cm");

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("in cm");

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("in cm");

        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("in cm");

        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("in kg");

        bmiLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel9.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel9.setText("BMI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(instructionTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bmiLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(bmiTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bmiLabel2)
                                    .addComponent(bmiLabel3)
                                    .addComponent(bmiLabel5)
                                    .addComponent(bmiLabel6)
                                    .addComponent(bmiLabel7)
                                    .addComponent(bmiLabel8)
                                    .addComponent(weightLabel)
                                    .addComponent(heightLabel)
                                    .addComponent(bmiLabel1)
                                    .addComponent(bmiLabel)
                                    .addComponent(bmiLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(physicalMetricsSubmitButton)
                .addGap(305, 305, 305))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instructionTitleLabel)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightLabel)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightLabel)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel2)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiLabel4)
                            .addComponent(bmiTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bmiTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmiLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmiTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bmiLabel9))
                .addGap(67, 67, 67)
                .addComponent(physicalMetricsSubmitButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void physicalMetricsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalMetricsSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalMetricsSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bmiLabel;
    private javax.swing.JLabel bmiLabel1;
    private javax.swing.JLabel bmiLabel2;
    private javax.swing.JLabel bmiLabel3;
    private javax.swing.JLabel bmiLabel4;
    private javax.swing.JLabel bmiLabel5;
    private javax.swing.JLabel bmiLabel6;
    private javax.swing.JLabel bmiLabel7;
    private javax.swing.JLabel bmiLabel8;
    private javax.swing.JLabel bmiLabel9;
    private javax.swing.JTextField bmiTextField;
    private javax.swing.JTextField bmiTextField1;
    private javax.swing.JTextField bmiTextField2;
    private javax.swing.JTextField bmiTextField3;
    private javax.swing.JTextField bmiTextField4;
    private javax.swing.JTextField bmiTextField5;
    private javax.swing.JTextField bmiTextField6;
    private javax.swing.JTextField bmiTextField7;
    private javax.swing.JTextField bmiTextField8;
    private javax.swing.JTextField bmiTextField9;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel instructionTitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton physicalMetricsSubmitButton;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
