/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainFrame;

/**
 *
 * @author emmanuelchibua
 */
public class PhysicalActivityLog extends javax.swing.JPanel {

    /**
     * Creates new form PhysicalActivityLog
     */
    public PhysicalActivityLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        physicalActivityLogLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        physicalActivityLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        endTimeLabel = new javax.swing.JLabel();
        caloriesBurntLabel = new javax.swing.JLabel();
        caloriesBurntForTheDayLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        dateTextField = new javax.swing.JTextField();
        stepsTakenTextField = new javax.swing.JTextField();
        startTimeTextField = new javax.swing.JTextField();
        physicalActivityTextField = new javax.swing.JTextField();
        sessionTimeTextField = new javax.swing.JTextField();
        sessionNameTextField = new javax.swing.JTextField();
        endTimeTextField = new javax.swing.JTextField();
        caloriesBurntTextField = new javax.swing.JTextField();
        caloriesBurntForTheDayTextField = new javax.swing.JTextField();
        physicalActivityLogSubmitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 102, 102));

        physicalActivityLogLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalActivityLogLabel.setForeground(new java.awt.Color(0, 102, 102));
        physicalActivityLogLabel.setText("Physical Activity Log");

        dateLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 102, 102));
        dateLabel.setText("Date");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Steps taken");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Sessions attended");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Session name");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Session time");

        physicalActivityLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalActivityLabel.setForeground(new java.awt.Color(0, 102, 102));
        physicalActivityLabel.setText("Physical Activity");

        startTimeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        startTimeLabel.setForeground(new java.awt.Color(0, 102, 102));
        startTimeLabel.setText("Start time");

        endTimeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        endTimeLabel.setForeground(new java.awt.Color(0, 102, 102));
        endTimeLabel.setText("End time");

        caloriesBurntLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        caloriesBurntLabel.setForeground(new java.awt.Color(0, 102, 102));
        caloriesBurntLabel.setText("Calories burnt");

        caloriesBurntForTheDayLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        caloriesBurntForTheDayLabel.setForeground(new java.awt.Color(0, 102, 102));
        caloriesBurntForTheDayLabel.setText("Calories burnt for the day");

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("No");

        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        stepsTakenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepsTakenTextFieldActionPerformed(evt);
            }
        });

        startTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeTextFieldActionPerformed(evt);
            }
        });

        physicalActivityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalActivityTextFieldActionPerformed(evt);
            }
        });

        sessionTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionTimeTextFieldActionPerformed(evt);
            }
        });

        sessionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionNameTextFieldActionPerformed(evt);
            }
        });

        endTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTimeTextFieldActionPerformed(evt);
            }
        });

        caloriesBurntTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caloriesBurntTextFieldActionPerformed(evt);
            }
        });

        caloriesBurntForTheDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caloriesBurntForTheDayTextFieldActionPerformed(evt);
            }
        });

        physicalActivityLogSubmitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalActivityLogSubmitButton.setForeground(new java.awt.Color(0, 102, 102));
        physicalActivityLogSubmitButton.setText("SUBMIT");
        physicalActivityLogSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalActivityLogSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(physicalActivityLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(physicalActivityLogSubmitButton)
                        .addGap(304, 304, 304))))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(dateLabel)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(physicalActivityLabel)
                    .addComponent(startTimeLabel)
                    .addComponent(caloriesBurntLabel)
                    .addComponent(caloriesBurntForTheDayLabel)
                    .addComponent(endTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(sessionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(physicalActivityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caloriesBurntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caloriesBurntForTheDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(physicalActivityLogLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabel)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stepsTakenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sessionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sessionTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(physicalActivityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(physicalActivityLabel))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startTimeLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caloriesBurntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caloriesBurntLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caloriesBurntForTheDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caloriesBurntForTheDayLabel))
                .addGap(47, 47, 47)
                .addComponent(physicalActivityLogSubmitButton)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void stepsTakenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepsTakenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepsTakenTextFieldActionPerformed

    private void startTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTimeTextFieldActionPerformed

    private void physicalActivityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalActivityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalActivityTextFieldActionPerformed

    private void sessionTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionTimeTextFieldActionPerformed

    private void sessionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionNameTextFieldActionPerformed

    private void endTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endTimeTextFieldActionPerformed

    private void caloriesBurntTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caloriesBurntTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caloriesBurntTextFieldActionPerformed

    private void caloriesBurntForTheDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caloriesBurntForTheDayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caloriesBurntForTheDayTextFieldActionPerformed

    private void physicalActivityLogSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalActivityLogSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalActivityLogSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caloriesBurntForTheDayLabel;
    private javax.swing.JTextField caloriesBurntForTheDayTextField;
    private javax.swing.JLabel caloriesBurntLabel;
    private javax.swing.JTextField caloriesBurntTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JTextField endTimeTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel physicalActivityLabel;
    private javax.swing.JLabel physicalActivityLogLabel;
    private javax.swing.JButton physicalActivityLogSubmitButton;
    private javax.swing.JTextField physicalActivityTextField;
    private javax.swing.JTextField sessionNameTextField;
    private javax.swing.JTextField sessionTimeTextField;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JTextField startTimeTextField;
    private javax.swing.JTextField stepsTakenTextField;
    // End of variables declaration//GEN-END:variables
}
