/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainFrame;

/**
 *
 * @author emmanuelchibua
 */
public class PhysicalMetrics extends javax.swing.JPanel {

    /**
     * Creates new form PhysicalMetrics
     */
    public PhysicalMetrics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weightLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        rightArmLabel = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        shoulderTextField = new javax.swing.JTextField();
        physicalMetricsSubmitButton = new javax.swing.JButton();
        instructionTitleLabel = new javax.swing.JLabel();
        shoulderLabel = new javax.swing.JLabel();
        chestLabel = new javax.swing.JLabel();
        leftArmLabel = new javax.swing.JLabel();
        rightArmTextField = new javax.swing.JTextField();
        leftArmTextField = new javax.swing.JTextField();
        chestTextField = new javax.swing.JTextField();
        hipTextField = new javax.swing.JTextField();
        rightThighTextField = new javax.swing.JTextField();
        leftThighTextField = new javax.swing.JTextField();
        rightCalfTextField = new javax.swing.JTextField();
        leftCalfTextField = new javax.swing.JTextField();
        hipLabel = new javax.swing.JLabel();
        rightThighLabel = new javax.swing.JLabel();
        leftThighLabel = new javax.swing.JLabel();
        rightCalfLabel = new javax.swing.JLabel();
        leftCalfLabel = new javax.swing.JLabel();
        shoulderDescriptionLabel = new javax.swing.JLabel();
        chestDescriptionLabel = new javax.swing.JLabel();
        rightArmDescriptionLabel = new javax.swing.JLabel();
        hipDescriptionLabel = new javax.swing.JLabel();
        leftArmDescriptionLabel = new javax.swing.JLabel();
        rightThighDescriptionLabel = new javax.swing.JLabel();
        leftThighDescriptionLabel = new javax.swing.JLabel();
        rightCalfDescriptionLabel = new javax.swing.JLabel();
        leftCalfDescriptionLabel = new javax.swing.JLabel();
        heightDescriptionLabel = new javax.swing.JLabel();
        weightDescriptionLabel = new javax.swing.JLabel();
        bmiLabel = new javax.swing.JLabel();
        bmiTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        weightLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        weightLabel.setForeground(new java.awt.Color(0, 102, 102));
        weightLabel.setText("Weight");

        heightLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        heightLabel.setForeground(new java.awt.Color(0, 102, 102));
        heightLabel.setText("Height");

        rightArmLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rightArmLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightArmLabel.setText("Right arm");

        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });

        physicalMetricsSubmitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalMetricsSubmitButton.setForeground(new java.awt.Color(0, 102, 102));
        physicalMetricsSubmitButton.setText("SUBMIT");
        physicalMetricsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalMetricsSubmitButtonActionPerformed(evt);
            }
        });

        instructionTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        instructionTitleLabel.setForeground(new java.awt.Color(0, 102, 102));
        instructionTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionTitleLabel.setText("Please input your body metric data below.");

        shoulderLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        shoulderLabel.setForeground(new java.awt.Color(0, 102, 102));
        shoulderLabel.setText("Shoulder");

        chestLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        chestLabel.setForeground(new java.awt.Color(0, 102, 102));
        chestLabel.setText("Chest");

        leftArmLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        leftArmLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftArmLabel.setText("Left arm");

        hipLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        hipLabel.setForeground(new java.awt.Color(0, 102, 102));
        hipLabel.setText("Hip");

        rightThighLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rightThighLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightThighLabel.setText("Right thigh");

        leftThighLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        leftThighLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftThighLabel.setText("Left thigh");

        rightCalfLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rightCalfLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightCalfLabel.setText("Right calf");

        leftCalfLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        leftCalfLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftCalfLabel.setText("Left calf");

        shoulderDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        shoulderDescriptionLabel.setText("in cm");

        chestDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        chestDescriptionLabel.setText("in cm");

        rightArmDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightArmDescriptionLabel.setText("in cm");

        hipDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        hipDescriptionLabel.setText("in cm");

        leftArmDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftArmDescriptionLabel.setText("in cm");

        rightThighDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightThighDescriptionLabel.setText("in cm");

        leftThighDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftThighDescriptionLabel.setText("in cm");

        rightCalfDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        rightCalfDescriptionLabel.setText("in cm");

        leftCalfDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        leftCalfDescriptionLabel.setText("in cm");

        heightDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        heightDescriptionLabel.setText("in cm");

        weightDescriptionLabel.setForeground(new java.awt.Color(0, 102, 102));
        weightDescriptionLabel.setText("in kg");

        bmiLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bmiLabel.setForeground(new java.awt.Color(0, 102, 102));
        bmiLabel.setText("BMI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(instructionTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hipLabel)
                                .addGap(18, 18, 18)
                                .addComponent(hipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chestLabel)
                                    .addComponent(leftArmLabel)
                                    .addComponent(rightThighLabel)
                                    .addComponent(leftThighLabel)
                                    .addComponent(rightCalfLabel)
                                    .addComponent(leftCalfLabel)
                                    .addComponent(weightLabel)
                                    .addComponent(heightLabel)
                                    .addComponent(shoulderLabel)
                                    .addComponent(rightArmLabel)
                                    .addComponent(bmiLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(shoulderTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rightArmTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leftArmTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chestTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rightThighTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leftThighTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rightCalfTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leftCalfTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bmiTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shoulderDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightArmDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftArmDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chestDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hipDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightThighDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftThighDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightCalfDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftCalfDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(physicalMetricsSubmitButton)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instructionTitleLabel)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightLabel)
                            .addComponent(weightDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightLabel)
                            .addComponent(heightDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoulderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shoulderLabel)
                            .addComponent(shoulderDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightArmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightArmLabel)
                            .addComponent(rightArmDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftArmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftArmLabel)
                            .addComponent(leftArmDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chestLabel)
                            .addComponent(chestDescriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hipLabel)
                            .addComponent(hipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hipDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightThighTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightThighLabel)
                            .addComponent(rightThighDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftThighTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftThighLabel)
                            .addComponent(leftThighDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightCalfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightCalfLabel)
                            .addComponent(rightCalfDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftCalfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftCalfLabel)
                            .addComponent(leftCalfDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bmiLabel))
                .addGap(50, 50, 50)
                .addComponent(physicalMetricsSubmitButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void physicalMetricsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalMetricsSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalMetricsSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bmiLabel;
    private javax.swing.JTextField bmiTextField;
    private javax.swing.JLabel chestDescriptionLabel;
    private javax.swing.JLabel chestLabel;
    private javax.swing.JTextField chestTextField;
    private javax.swing.JLabel heightDescriptionLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel hipDescriptionLabel;
    private javax.swing.JLabel hipLabel;
    private javax.swing.JTextField hipTextField;
    private javax.swing.JLabel instructionTitleLabel;
    private javax.swing.JLabel leftArmDescriptionLabel;
    private javax.swing.JLabel leftArmLabel;
    private javax.swing.JTextField leftArmTextField;
    private javax.swing.JLabel leftCalfDescriptionLabel;
    private javax.swing.JLabel leftCalfLabel;
    private javax.swing.JTextField leftCalfTextField;
    private javax.swing.JLabel leftThighDescriptionLabel;
    private javax.swing.JLabel leftThighLabel;
    private javax.swing.JTextField leftThighTextField;
    private javax.swing.JButton physicalMetricsSubmitButton;
    private javax.swing.JLabel rightArmDescriptionLabel;
    private javax.swing.JLabel rightArmLabel;
    private javax.swing.JTextField rightArmTextField;
    private javax.swing.JLabel rightCalfDescriptionLabel;
    private javax.swing.JLabel rightCalfLabel;
    private javax.swing.JTextField rightCalfTextField;
    private javax.swing.JLabel rightThighDescriptionLabel;
    private javax.swing.JLabel rightThighLabel;
    private javax.swing.JTextField rightThighTextField;
    private javax.swing.JLabel shoulderDescriptionLabel;
    private javax.swing.JLabel shoulderLabel;
    private javax.swing.JTextField shoulderTextField;
    private javax.swing.JLabel weightDescriptionLabel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
