/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainFrame;

/**
 *
 * @author emmanuelchibua
 */
public class View1c extends javax.swing.JPanel {

    /**
     * Creates new form View1c
     */
    public View1c() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        challengerNameLabel = new javax.swing.JLabel();
        challengerNameTextField = new javax.swing.JTextField();
        downloadScheduleButton = new javax.swing.JButton();
        foodIntakeLogViewButton = new javax.swing.JButton();
        physicalMetricsViewButton = new javax.swing.JButton();
        physicalActivitiesLogViewButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setForeground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        challengerNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        challengerNameLabel.setForeground(new java.awt.Color(0, 102, 102));
        challengerNameLabel.setText("Challenger Name");

        challengerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challengerNameTextFieldActionPerformed(evt);
            }
        });

        downloadScheduleButton.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        downloadScheduleButton.setForeground(new java.awt.Color(0, 102, 102));
        downloadScheduleButton.setText("Download schedule");
        downloadScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadScheduleButtonActionPerformed(evt);
            }
        });

        foodIntakeLogViewButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        foodIntakeLogViewButton.setForeground(new java.awt.Color(0, 102, 102));
        foodIntakeLogViewButton.setText("Food intake log");
        foodIntakeLogViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodIntakeLogViewButtonActionPerformed(evt);
            }
        });

        physicalMetricsViewButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalMetricsViewButton.setForeground(new java.awt.Color(0, 102, 102));
        physicalMetricsViewButton.setText("Physical Meterics");
        physicalMetricsViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalMetricsViewButtonActionPerformed(evt);
            }
        });

        physicalActivitiesLogViewButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        physicalActivitiesLogViewButton.setForeground(new java.awt.Color(0, 102, 102));
        physicalActivitiesLogViewButton.setText("Physical Activities log");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(challengerNameLabel)
                        .addGap(34, 34, 34)
                        .addComponent(challengerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(downloadScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(foodIntakeLogViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(physicalMetricsViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(physicalActivitiesLogViewButton)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(challengerNameLabel)
                    .addComponent(challengerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadScheduleButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodIntakeLogViewButton)
                    .addComponent(physicalMetricsViewButton)
                    .addComponent(physicalActivitiesLogViewButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void challengerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challengerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_challengerNameTextFieldActionPerformed

    private void downloadScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadScheduleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadScheduleButtonActionPerformed

    private void foodIntakeLogViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodIntakeLogViewButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodIntakeLogViewButtonActionPerformed

    private void physicalMetricsViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalMetricsViewButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicalMetricsViewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel challengerNameLabel;
    private javax.swing.JTextField challengerNameTextField;
    private javax.swing.JButton downloadScheduleButton;
    private javax.swing.JButton foodIntakeLogViewButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton physicalActivitiesLogViewButton;
    private javax.swing.JButton physicalMetricsViewButton;
    // End of variables declaration//GEN-END:variables
}
